isso informará, no deploy, qual arquivo está mal configurado

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -51,7 +51,12 @@ jobs:
             --minify \
             --baseURL "${{ steps.pages.outputs.base_url }}/"  
       - name: Check public folder exists
-        run: test -d public && echo "Public folder exists" || (echo "Public folder missing" && exit 1)         
+        run: test -d public && echo "Public folder exists" || (echo "Public folder missing" && exit 1) 
+      - name: List contents of public directory
+        run: |
+          echo "Listing files in public/"
+          find public -type f -exec ls -l {} \;
+                
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
